/**
 * Storage abstraction (blueprint §10, §14.D6).
 *
 * Feature code never touches `fs` or the S3 client directly: it asks the
 * adapter to put/read/delete an object by KEY and visibility. Keys are
 * opaque, randomised paths ("products/2026/09/k8s7…q.webp") generated by
 * `buildStorageKey`, never derived from a client filename, so a stored key
 * can be echoed in URLs and logs without a path-traversal or XSS worry.
 *
 * PUBLIC and PRIVATE objects live in separate roots (local: two directories;
 * S3: two key prefixes) so a bucket policy or a route handler can grant read
 * on one without ever being able to reach the other.
 */

export type StorageVisibility = "PUBLIC" | "PRIVATE";

export type PutObjectInput = {
  key: string;
  body: Buffer | Uint8Array;
  contentType: string;
  visibility: StorageVisibility;
  /** Overrides the default immutable-year policy for public objects. */
  cacheControl?: string;
};

export type PutObjectResult = {
  key: string;
  /** Public URL for PUBLIC objects; null for PRIVATE (served via admin API). */
  url: string | null;
};

export type StorageStat = {
  size: number;
  lastModified: Date | null;
};

export interface StorageAdapter {
  readonly driver: "local" | "s3";
  put(input: PutObjectInput): Promise<PutObjectResult>;
  delete(key: string, visibility?: StorageVisibility): Promise<void>;
  /** URL a browser can load a PUBLIC object from. */
  publicUrl(key: string): string;
  /** Whole object in memory; fine for images, avoid for large videos. */
  read(key: string, visibility?: StorageVisibility): Promise<Buffer>;
  /** Streaming read for route handlers; `range` is inclusive byte offsets. */
  readStream(
    key: string,
    visibility?: StorageVisibility,
    range?: { start: number; end: number },
  ): Promise<ReadableStream<Uint8Array>>;
  exists(key: string, visibility?: StorageVisibility): Promise<boolean>;
  stat(key: string, visibility?: StorageVisibility): Promise<StorageStat | null>;
}

/** Public objects never change (keys are random), so cache them forever. */
export const IMMUTABLE_CACHE_CONTROL = "public, max-age=31536000, immutable";

/**
 * Key grammar: lowercase segments of [a-z0-9._-], joined by "/", no leading
 * slash, no empty or dot-only segments, at most 200 chars. Anything else is a
 * bug or an attack and is refused before it reaches a filesystem call.
 */
const KEY_SEGMENT = /^[a-z0-9][a-z0-9._-]{0,63}$/;

export function isSafeStorageKey(key: string): boolean {
  if (typeof key !== "string" || key.length === 0 || key.length > 200) return false;
  if (key.includes("\\") || key.includes("\0")) return false;
  const segments = key.split("/");
  return segments.every(
    (segment) => KEY_SEGMENT.test(segment) && segment !== "." && segment !== "..",
  );
}

export function assertSafeStorageKey(key: string): void {
  if (!isSafeStorageKey(key)) {
    throw new Error(`Refusing unsafe storage key "${key.slice(0, 80)}".`);
  }
}
