/**
 * The demo product catalogue (blueprint §12) as DATA. Prices are rupees and
 * converted to paise by the products module; attribute values are the
 * slugified labels from prisma/seed/modules/attributes.ts; `axes` name the
 * variant-defining attributes and the values to generate combinations from
 * (validated against the category's effective set at seed time, A1/A5).
 *
 * Every leaf category has at least one product. `seller` is the demo seller
 * number (1-5 ACTIVE, 7 UNDER_REVIEW, 8 SUSPENDED) or null for a
 * platform-owned listing.
 */
export type CustomizationSpec = {
  type: string;
  label: string;
  helpText?: string;
  placeholder?: string;
  isRequired?: boolean;
  minLength?: number;
  maxLength?: number;
  maxFiles?: number;
  allowedMimeTypes?: string[];
  choices?: Array<{ value: string; label: string; priceDeltaPaise?: number }>;
  priceDeltaPaise?: number;
};

export type ProductSpec = {
  n: number;
  title: string;
  /** Leaf category slug. */
  category: string;
  seller: number | null;
  /** Rupees. */
  price: number;
  sale?: number;
  /** When a sale price is set: active (default), future or past window. */
  saleWindow?: "active" | "future" | "past";
  cost: number;
  tax: 0 | 500 | 1200;
  hsn: string;
  weight: number;
  /** cm: length × width × height. */
  dims?: [number, number, number];
  brand?: string;
  short: string;
  desc: string;
  flags?: { featured?: boolean; newArrival?: boolean; bestseller?: boolean; trending?: boolean };
  tags: string[];
  /** attribute code → value slug | slugs | number | text | boolean */
  attrs?: Record<string, string | string[] | number | boolean>;
  /** attribute code → value slugs (variant axes). */
  axes?: Record<string, string[]>;
  /** value slug → price delta in rupees applied to variants carrying it. */
  variantPrices?: Record<string, number>;
  /** Opening stock per variant: a number for all, "low" (1-3), "out" (0) or a list per variant. */
  stock: number | "low" | "out" | number[];
  status?: "DRAFT" | "ARCHIVED";
  /** Number of generated images (1-3) or a legacy photo group name. */
  images?: number | { legacy: string; count?: number };
  /** Days ago the product was created (drives "new arrivals"). */
  ageDays: number;
  customization?: CustomizationSpec[];
  minOrderQty?: number;
  maxOrderQty?: number;
  shippingNote?: string;
};

const IMAGE_MIMES = ["image/jpeg", "image/png", "image/webp"];

export const PRODUCTS: ProductSpec[] = [
  // ---- Home & Living (Kalakriti Studio = 1, Rustic Roots = 8) ---------------
  {
    n: 1,
    title: "Macramé Wall Hanging – Luna",
    category: "wall-decor",
    seller: 1,
    price: 1499,
    sale: 1299,
    cost: 620,
    tax: 500,
    hsn: "6304",
    weight: 450,
    dims: [60, 4, 90],
    short: "Hand-knotted cotton macramé on a driftwood dowel.",
    desc: "<h3>Slow-made, knot by knot</h3><p>Luna is knotted from 3 mm unbleached cotton rope on a hand-finished driftwood dowel. The crescent pattern takes about six hours to complete.</p><ul><li>60 cm wide, 90 cm drop including fringe</li><li>Ready to hang - loop included</li><li>Dust gently; avoid direct sun to keep the cotton bright</li></ul>",
    flags: { featured: true, bestseller: true },
    tags: ["boho", "home-decor", "handmade"],
    attrs: { material: "cotton", finish: "natural", theme: ["nature"], style: "bohemian", weight: 450, dimensions: "60 × 4 × 90 cm" },
    axes: { colour: ["white", "beige", "mustard"] },
    stock: 12,
    images: 3,
    ageDays: 110,
  },
  {
    n: 2,
    title: "Hand-painted Terracotta Wall Plates (Set of 3)",
    category: "wall-decor",
    seller: 1,
    price: 2199,
    cost: 900,
    tax: 1200,
    hsn: "6913",
    weight: 900,
    dims: [30, 30, 4],
    short: "Three graduated plates with folk motifs in earthy tones.",
    desc: "<p>A trio of wheel-thrown terracotta plates (25, 20 and 15 cm) painted with Rajasthani folk motifs and sealed with a matte varnish. Each set is painted by hand, so motifs vary slightly.</p><p>Hooks are fitted at the back for hanging.</p>",
    tags: ["home-decor", "folk-art", "handmade"],
    attrs: { material: "terracotta", finish: "hand-painted", theme: ["tribal", "floral"], style: "folk", weight: 900 },
    axes: { colour: ["multicolour"] },
    stock: 6,
    images: 2,
    ageDays: 95,
  },
  {
    n: 3,
    title: "Lavender Soy Candle in Amber Jar",
    category: "candles",
    seller: 1,
    price: 649,
    cost: 240,
    tax: 1200,
    hsn: "3406",
    weight: 220,
    short: "Hand-poured soy wax, 40-hour burn, cotton wick.",
    desc: "<p>Pure soy wax poured by hand into a reusable amber glass jar and scented with French lavender essential oil. Burns clean for about 40 hours.</p><ul><li>200 g wax, 40 h burn time</li><li>Lead-free cotton wick</li><li>Trim the wick to 5 mm before each burn</li></ul>",
    flags: { bestseller: true },
    tags: ["candles", "self-care", "gift"],
    attrs: { material: "glass", fragrance: "lavender", finish: "matte", style: "minimalist", weight: 220 },
    axes: { colour: ["purple"] },
    stock: 30,
    images: 2,
    ageDays: 140,
  },
  {
    n: 4,
    title: "Sandalwood Candle in Ceramic Bowl",
    category: "candles",
    seller: 1,
    price: 899,
    cost: 360,
    tax: 1200,
    hsn: "3406",
    weight: 380,
    short: "Woody sandalwood in a hand-glazed stoneware bowl you keep.",
    desc: "<p>Soy-coconut wax blend scented with Mysore sandalwood, poured into a stoneware bowl glazed in the studio. When the candle is done, the bowl becomes a trinket dish.</p>",
    tags: ["candles", "gift", "festive"],
    attrs: { material: "ceramic", fragrance: "sandalwood", finish: "glossy", style: "modern", weight: 380 },
    axes: { colour: ["beige", "teal"] },
    stock: "low",
    images: 2,
    ageDays: 60,
  },
  {
    n: 5,
    title: "Terracotta Planter with Saucer (Medium)",
    category: "planters-and-vases",
    seller: 8,
    price: 549,
    cost: 210,
    tax: 500,
    hsn: "6912",
    weight: 1100,
    dims: [18, 18, 17],
    short: "Breathable clay planter with a matching drip saucer.",
    desc: "<p>Unglazed terracotta lets roots breathe - ideal for succulents and herbs. Fired at low temperature in a traditional kiln; minor colour variation is natural.</p>",
    tags: ["garden", "planters"],
    attrs: { material: "terracotta", finish: "natural", style: "rustic", size: "medium", weight: 1100, dimensions: "18 × 18 × 17 cm" },
    axes: { colour: ["brown", "white"] },
    stock: 8,
    images: 2,
    ageDays: 180,
  },
  {
    n: 6,
    title: "Hand-thrown Ceramic Bud Vase",
    category: "planters-and-vases",
    seller: 1,
    price: 1099,
    cost: 420,
    tax: 1200,
    hsn: "6913",
    weight: 400,
    dims: [9, 9, 16],
    short: "Small-batch stoneware with a reactive glaze.",
    desc: "<p>Thrown on the wheel and glazed with a reactive finish that pools differently on every piece. Holds a single stem or a small posy.</p><p>Watertight and food-safe glaze.</p>",
    flags: { newArrival: true },
    tags: ["ceramics", "home-decor", "new"],
    attrs: { material: "ceramic", finish: "glossy", style: "minimalist", theme: ["abstract"], weight: 400 },
    axes: { colour: ["teal", "white", "mustard"] },
    stock: 15,
    images: 3,
    ageDays: 12,
  },
  {
    n: 7,
    title: "Block-printed Cotton Cushion Cover",
    category: "cushions-and-throws",
    seller: 2,
    price: 499,
    cost: 190,
    tax: 500,
    hsn: "6304",
    weight: 180,
    short: "Bagru hand-block print on 100% cotton with a hidden zip.",
    desc: "<p>Printed with hand-carved wooden blocks in Bagru using natural dyes, then stitched with a concealed zip. Cover only; insert not included.</p><ul><li>Small 30 × 30 cm, Medium 40 × 40 cm, Large 50 × 50 cm</li><li>Machine wash cold, inside out</li></ul>",
    flags: { bestseller: true },
    tags: ["block-print", "cushions", "home-decor"],
    attrs: { material: "cotton", fabric: "cotton", finish: "natural", theme: ["floral"], style: "traditional", weight: 180 },
    axes: { colour: ["indigo", "red", "mustard"], size: ["small", "medium", "large"] },
    variantPrices: { medium: 100, large: 200 },
    stock: 10,
    images: 3,
    ageDays: 130,
  },
  {
    n: 8,
    title: "Kantha Embroidered Cotton Throw",
    category: "cushions-and-throws",
    seller: 2,
    price: 2899,
    cost: 1300,
    tax: 500,
    hsn: "6304",
    weight: 800,
    dims: [220, 140, 1],
    short: "Reversible kantha stitch over layered vintage cotton.",
    desc: "<p>Three layers of upcycled cotton saree held together with thousands of running kantha stitches. Reversible, with a different print on each side.</p>",
    flags: { featured: true },
    tags: ["kantha", "throws", "upcycled"],
    attrs: { material: "cotton", fabric: "cotton", finish: "natural", theme: ["floral"], style: "vintage", weight: 800, dimensions: "220 × 140 cm" },
    axes: { colour: ["multicolour"], size: ["large"] },
    stock: 5,
    images: 2,
    ageDays: 75,
  },
  {
    n: 9,
    title: "Mango Wood Serving Platter with Handles",
    category: "kitchen-and-dining",
    seller: 1,
    price: 1299,
    sale: 1099,
    cost: 480,
    tax: 1200,
    hsn: "4419",
    weight: 650,
    dims: [40, 20, 2],
    short: "Food-safe oiled mango wood, carved from a single plank.",
    desc: "<p>Carved from sustainably harvested mango wood and finished with food-grade mineral oil. Great for cheese, bread or a chai tray.</p><p>Wipe clean; re-oil every few months.</p>",
    flags: { trending: true },
    tags: ["kitchen", "serveware", "wood"],
    attrs: { material: "wood", finish: "natural", style: "rustic", weight: 650, dimensions: "40 × 20 × 2 cm" },
    axes: { colour: ["brown"] },
    stock: 10,
    images: 2,
    ageDays: 88,
  },
  {
    n: 10,
    title: "Blue Pottery Coasters (Set of 4)",
    category: "kitchen-and-dining",
    seller: 1,
    price: 799,
    cost: 300,
    tax: 1200,
    hsn: "6913",
    weight: 380,
    short: "Jaipur blue pottery with a cork backing.",
    desc: "<p>Classic Jaipur blue pottery - quartz body, hand-painted floral motifs, glazed and cork-backed so they never scratch a table.</p>",
    tags: ["kitchen", "blue-pottery", "gift"],
    attrs: { material: "ceramic", finish: "glossy", theme: ["floral"], style: "traditional", weight: 380 },
    axes: { colour: ["blue", "white"] },
    stock: 20,
    images: 2,
    ageDays: 100,
  },
  {
    n: 11,
    title: "Hammered Copper Water Bottle",
    category: "kitchen-and-dining",
    seller: null,
    brand: "DIY Baazar Originals",
    price: 1199,
    cost: 520,
    tax: 1200,
    hsn: "7418",
    weight: 320,
    dims: [7, 7, 27],
    short: "950 ml pure copper, hand-hammered, leak-proof cap.",
    desc: "<p>Made from 99% pure copper and hammered by hand in Moradabad. Store water overnight for the traditional Ayurvedic benefit.</p><ul><li>Capacity 950 ml</li><li>Leak-proof screw cap</li><li>Clean with lemon and salt</li></ul>",
    flags: { bestseller: true },
    tags: ["kitchen", "copper", "wellness"],
    attrs: { material: "copper", finish: "polished", style: "traditional", capacity: 950, weight: 320 },
    axes: { colour: ["brown"] },
    stock: 40,
    images: 2,
    ageDays: 150,
  },
  {
    n: 12,
    title: "Jute Storage Baskets (Set of 2)",
    category: "storage-and-organisers",
    seller: 8,
    price: 999,
    cost: 400,
    tax: 500,
    hsn: "4602",
    weight: 700,
    short: "Braided jute with cotton handles, two nesting sizes.",
    desc: "<p>Hand-braided jute rope baskets that hold their shape. Use for laundry, toys or plants (with a liner).</p>",
    tags: ["storage", "jute", "eco-friendly"],
    attrs: { material: "jute", finish: "natural", style: "rustic", size: "medium", weight: 700 },
    axes: { colour: ["beige", "grey"] },
    stock: "low",
    images: 2,
    ageDays: 160,
  },
  {
    n: 13,
    title: "Cane Tray Organiser",
    category: "storage-and-organisers",
    seller: 1,
    price: 749,
    cost: 280,
    tax: 500,
    hsn: "4602",
    weight: 350,
    dims: [35, 25, 6],
    short: "Woven cane tray for keys, mail and remotes.",
    desc: "<p>Woven from Assam cane on a wooden base and sealed with a clear lacquer. Currently out of stock - the next batch is being woven.</p>",
    tags: ["storage", "cane"],
    attrs: { material: "cane", finish: "natural", style: "minimalist", weight: 350, dimensions: "35 × 25 × 6 cm" },
    axes: { colour: ["beige"] },
    stock: "out",
    images: 1,
    ageDays: 200,
  },
  {
    n: 14,
    title: "Brass Diya Table Lamp",
    category: "lamps-and-lighting",
    seller: 1,
    price: 2499,
    cost: 1100,
    tax: 1200,
    hsn: "9405",
    weight: 1200,
    dims: [16, 16, 32],
    short: "Antique-finish brass diya on a turned wood base, with a warm LED bulb.",
    desc: "<p>A traditional brass diya form re-imagined as a table lamp. Antique-finished brass on a turned sheesham base, wired with a 2-pin plug and a warm 4 W LED bulb.</p>",
    flags: { featured: true },
    tags: ["lighting", "brass", "festive"],
    attrs: { material: "brass", finish: "antique", theme: ["festive", "spiritual"], style: "traditional", weight: 1200, dimensions: "16 × 16 × 32 cm" },
    axes: { colour: ["gold"] },
    stock: 7,
    images: 3,
    ageDays: 70,
  },
  {
    n: 15,
    title: "Bamboo Pendant Lampshade",
    category: "lamps-and-lighting",
    seller: 1,
    price: 1799,
    cost: 700,
    tax: 1200,
    hsn: "9405",
    weight: 500,
    dims: [30, 30, 28],
    short: "Hand-woven bamboo shade that throws a dappled light.",
    desc: "<p>Woven from split bamboo in a Tripura weaving cluster. Shade only - fits any E27 pendant fitting.</p>",
    flags: { newArrival: true },
    tags: ["lighting", "bamboo", "boho"],
    attrs: { material: "bamboo", finish: "natural", style: "bohemian", weight: 500, dimensions: "30 × 30 × 28 cm" },
    axes: { colour: ["beige", "brown"] },
    stock: 9,
    images: 2,
    ageDays: 8,
  },
  {
    n: 16,
    title: "Carved Wooden Nameplate (Personalised)",
    category: "woodcrafts",
    seller: 1,
    price: 1499,
    cost: 550,
    tax: 1200,
    hsn: "4420",
    weight: 900,
    dims: [40, 15, 2],
    short: "Your family name hand-carved into solid sheesham, weatherproof finish.",
    desc: "<h3>Made to order</h3><p>Tell us the name and pick a motif; we carve it into a 40 × 15 cm sheesham plank and seal it with an outdoor-grade lacquer. Ships in 5-7 working days.</p><p>Up to 24 characters. Mounting screws included.</p>",
    tags: ["personalised", "woodcraft", "housewarming"],
    attrs: { material: "wood", finish: "natural", theme: ["quotes"], style: "traditional", weight: 900, dimensions: "40 × 15 × 2 cm" },
    axes: { colour: ["brown", "black"] },
    stock: 12,
    images: 2,
    ageDays: 120,
    shippingNote: "Made to order - dispatches in 5-7 working days.",
    customization: [
      { type: "ENGRAVING", label: "Name to carve", placeholder: "The Sharmas", isRequired: true, minLength: 2, maxLength: 24 },
      {
        type: "DESIGN_SELECT",
        label: "Motif",
        isRequired: true,
        choices: [
          { value: "lotus", label: "Lotus" },
          { value: "peacock", label: "Peacock", priceDeltaPaise: 20000 },
          { value: "geometric", label: "Geometric border" },
        ],
      },
      { type: "INSTRUCTIONS", label: "Special instructions", maxLength: 200 },
    ],
  },
  {
    n: 17,
    title: "Hand-carved Wooden Elephant Figurine",
    category: "woodcrafts",
    seller: 1,
    price: 899,
    cost: 320,
    tax: 1200,
    hsn: "4420",
    weight: 420,
    dims: [15, 7, 12],
    short: "Channapatna-style lacquered elephant, 15 cm.",
    desc: "<p>Turned and carved from ivory wood, then lacquered with natural colours in the Channapatna tradition. A classic housewarming gift.</p>",
    tags: ["woodcraft", "gift", "animals"],
    attrs: { material: "wood", finish: "polished", theme: ["animals"], style: "folk", weight: 420 },
    axes: { colour: ["brown"] },
    stock: 14,
    images: 2,
    ageDays: 90,
  },

  // ---- Fashion (Anokhi Threads = 2, platform) --------------------------------
  {
    n: 18,
    title: "Men's Indigo Block-print Kurta",
    category: "mens-kurta",
    seller: 2,
    price: 1899,
    sale: 1599,
    cost: 780,
    tax: 500,
    hsn: "6205",
    weight: 350,
    short: "Straight-cut cotton kurta, hand-block printed in Bagru indigo.",
    desc: "<p>Soft 60s-count cotton, hand-block printed with natural indigo. Straight cut with side slits and a mandarin collar.</p><ul><li>Length 40 in</li><li>Machine wash cold separately for the first two washes</li></ul>",
    flags: { bestseller: true },
    tags: ["kurta", "block-print", "menswear"],
    attrs: { fabric: "cotton", pattern: "block-printed", occasion: ["everyday", "diwali"], style: "traditional" },
    axes: { size: ["s", "m", "l", "xl"], colour: ["indigo"] },
    variantPrices: { xl: 100 },
    stock: [8, 10, 10, 4],
    images: 3,
    ageDays: 125,
  },
  {
    n: 19,
    title: "Men's Khadi Kurta, Mandarin Collar",
    category: "mens-kurta",
    seller: 2,
    price: 2299,
    cost: 950,
    tax: 500,
    hsn: "6205",
    weight: 380,
    short: "Handspun, handwoven khadi in natural white and beige.",
    desc: "<p>Hand-spun and hand-woven khadi from a Gujarat cooperative. Breathable, softens with every wash. Long sleeves with a concealed placket.</p>",
    tags: ["kurta", "khadi", "menswear"],
    attrs: { fabric: "khadi", pattern: "solid", occasion: ["everyday"], style: "minimalist" },
    axes: { size: ["m", "l", "xl"], colour: ["white", "beige"] },
    stock: 5,
    images: 2,
    ageDays: 65,
  },
  {
    n: 20,
    title: "Women's Chanderi Kurta with Gota Work",
    category: "womens-kurta",
    seller: 2,
    price: 2799,
    cost: 1200,
    tax: 500,
    hsn: "6204",
    weight: 320,
    short: "Sheer chanderi with hand-applied gota patti on the neckline.",
    desc: "<p>Chanderi silk-cotton with gota patti embroidery worked by hand around the neck and cuffs. Comes with a matching cotton slip.</p>",
    flags: { featured: true },
    tags: ["kurta", "festive", "womenswear"],
    attrs: { fabric: "chanderi", pattern: "embroidered", occasion: ["wedding", "diwali"], style: "traditional" },
    axes: { size: ["s", "m", "l"], colour: ["pink", "teal"] },
    stock: [6, 6, 4, 5, 5, 3],
    images: 3,
    ageDays: 45,
  },
  {
    n: 21,
    title: "Women's Mulmul Kurta, Floral",
    category: "womens-kurta",
    seller: 2,
    price: 1499,
    cost: 600,
    tax: 500,
    hsn: "6204",
    weight: 260,
    short: "Featherlight mulmul with a hand-printed floral jaal.",
    desc: "<p>Mulmul cotton so fine it floats. Hand-block printed floral all-over with a V-neck and three-quarter sleeves. Perfect for Indian summers.</p>",
    flags: { newArrival: true },
    tags: ["kurta", "summer", "womenswear"],
    attrs: { fabric: "mulmul", pattern: "floral", occasion: ["everyday"], style: "contemporary" },
    axes: { size: ["xs", "s", "m", "l"], colour: ["yellow"] },
    stock: 12,
    images: 2,
    ageDays: 6,
  },
  {
    n: 22,
    title: "Handloom Cotton Saree, Temple Border",
    category: "sarees",
    seller: 2,
    price: 3499,
    cost: 1500,
    tax: 500,
    hsn: "5208",
    weight: 500,
    short: "Kanchi-cotton saree with a woven temple border and blouse piece.",
    desc: "<p>Woven on a pit loom in Chettinad. Contrast temple border, 6.3 m including an 80 cm blouse piece.</p>",
    flags: { trending: true },
    tags: ["saree", "handloom", "festive"],
    attrs: { fabric: "cotton", pattern: "ethnic", occasion: ["wedding", "diwali"] },
    axes: { size: ["free-size"], colour: ["red", "green"] },
    stock: 3,
    images: 2,
    ageDays: 80,
  },
  {
    n: 23,
    title: "Hand-painted Kalamkari Silk Saree",
    category: "sarees",
    seller: 2,
    price: 6999,
    cost: 3200,
    tax: 500,
    hsn: "5007",
    weight: 550,
    short: "Pen kalamkari on pure silk - a month in the making.",
    desc: "<p>Drawn freehand with a bamboo pen and coloured with vegetable dyes over twenty-three stages. Each saree is a one-off.</p>",
    flags: { featured: true },
    tags: ["saree", "kalamkari", "silk", "luxury"],
    attrs: { fabric: "silk", pattern: "ethnic", occasion: ["wedding"] },
    axes: { size: ["free-size"], colour: ["maroon"] },
    stock: "low",
    images: 3,
    ageDays: 30,
  },
  {
    n: 24,
    title: "Bandhani Georgette Dupatta",
    category: "dupattas-and-stoles",
    seller: 2,
    price: 899,
    cost: 350,
    tax: 500,
    hsn: "6214",
    weight: 120,
    short: "Tie-dyed in Bhuj with thousands of tiny knots.",
    desc: "<p>Genuine bandhani - each dot is a knot tied by hand before dyeing. 2.25 m georgette with a hand-rolled edge.</p>",
    flags: { bestseller: true },
    tags: ["dupatta", "bandhani", "festive"],
    attrs: { fabric: "georgette", pattern: "ethnic", occasion: ["everyday", "diwali"] },
    axes: { size: ["free-size"], colour: ["red", "yellow", "green", "blue"] },
    stock: 10,
    images: 2,
    ageDays: 140,
  },
  {
    n: 25,
    title: "Handwoven Merino Wool Stole",
    category: "dupattas-and-stoles",
    seller: 2,
    price: 1599,
    cost: 700,
    tax: 500,
    hsn: "6214",
    weight: 200,
    short: "Kullu-woven stole with a striped border.",
    desc: "<p>Woven on a frame loom in Kullu from soft merino, finished with twisted tassels. 70 × 200 cm.</p>",
    tags: ["stole", "wool", "winter"],
    attrs: { fabric: "wool", pattern: "striped", occasion: ["everyday"] },
    axes: { size: ["free-size"], colour: ["grey", "maroon"] },
    stock: 6,
    images: 2,
    ageDays: 55,
  },
  {
    n: 26,
    title: "Handcrafted Jute Tote Bag",
    category: "bags",
    seller: null,
    brand: "DIY Baazar Originals",
    price: 799,
    cost: 300,
    tax: 500,
    hsn: "4202",
    weight: 350,
    dims: [40, 12, 35],
    short: "Roomy everyday tote in natural jute with a zip pocket.",
    desc: "<p>Laminated natural jute with cotton-webbing handles and an inside zip pocket. Carries a 15-inch laptop and the week's groceries.</p>",
    flags: { bestseller: true },
    tags: ["bags", "jute", "eco-friendly"],
    attrs: { material: "jute", "closure-type": "zip", pattern: "solid", occasion: ["everyday"] },
    axes: { colour: ["beige", "black"] },
    stock: 30,
    images: { legacy: "tote", count: 3 },
    ageDays: 170,
  },
  {
    n: 27,
    title: "Embroidered Sling Bag",
    category: "bags",
    seller: 2,
    price: 1299,
    cost: 520,
    tax: 500,
    hsn: "4202",
    weight: 300,
    dims: [24, 8, 18],
    short: "Kutch mirror-work embroidery with an adjustable strap.",
    desc: "<p>Hand-embroidered by Kutchi artisans with mirror work and chain stitch. Cotton lining, magnetic flap and an adjustable strap.</p>",
    flags: { trending: true },
    tags: ["bags", "embroidered", "boho"],
    attrs: { material: "fabric", "closure-type": "magnetic", pattern: "embroidered", occasion: ["everyday", "wedding"] },
    axes: { colour: ["multicolour"] },
    stock: 8,
    images: { legacy: "sling", count: 3 },
    ageDays: 60,
  },
  {
    n: 28,
    title: "Hand-stitched Leather Handbag",
    category: "bags",
    seller: null,
    brand: "DIY Baazar Originals",
    price: 3499,
    sale: 2999,
    cost: 1600,
    tax: 1200,
    hsn: "4202",
    weight: 750,
    dims: [32, 12, 26],
    short: "Full-grain leather, saddle-stitched by hand in Kanpur.",
    desc: "<p>Full-grain buffalo leather that develops a patina with use. Saddle-stitched with waxed thread, brass hardware, cotton twill lining.</p>",
    flags: { featured: true },
    tags: ["bags", "leather", "luxury"],
    attrs: { material: "leather", "closure-type": "magnetic", pattern: "solid", occasion: ["everyday", "corporate"] },
    axes: { colour: ["brown", "black"] },
    stock: 6,
    images: { legacy: "handbags", count: 3 },
    ageDays: 100,
  },
  {
    n: 29,
    title: "Mini Potli Bag with Tassels",
    category: "bags",
    seller: 2,
    price: 649,
    cost: 240,
    tax: 500,
    hsn: "4202",
    weight: 120,
    short: "Brocade potli with silk tassels - a festive essential.",
    desc: "<p>Banarasi brocade potli with a drawstring closure and hand-tied silk tassels. Holds a phone, lipstick and cards.</p>",
    tags: ["bags", "festive", "wedding"],
    attrs: { material: "fabric", "closure-type": "drawstring", pattern: "ethnic", occasion: ["wedding", "diwali"] },
    axes: { colour: ["pink", "gold", "green"] },
    stock: 15,
    images: { legacy: "minibags", count: 3 },
    ageDays: 85,
  },
  {
    n: 30,
    title: "Block-print Cotton Wallet",
    category: "bags",
    seller: 2,
    price: 499,
    cost: 180,
    tax: 500,
    hsn: "4202",
    weight: 90,
    short: "Slim bi-fold wallet in hand-block-printed canvas.",
    desc: "<p>Canvas-weight cotton, block printed and lined with plain cotton. Six card slots, a zip coin pocket and a note sleeve.</p>",
    tags: ["bags", "wallet", "block-print"],
    attrs: { material: "cotton", "closure-type": "zip", pattern: "block-printed", occasion: ["everyday"] },
    axes: { colour: ["blue", "red"] },
    stock: 20,
    images: { legacy: "wallet", count: 3 },
    ageDays: 115,
  },
  {
    n: 31,
    title: "Embroidered Punjabi Jutti",
    category: "footwear",
    seller: 2,
    price: 1499,
    cost: 620,
    tax: 500,
    hsn: "6403",
    weight: 400,
    short: "Zari and thread embroidery on soft leather, hand-stitched sole.",
    desc: "<p>Made in Patiala with a leather sole stitched by hand. The upper carries zari and thread embroidery. Breaks in after a few wears.</p><p>Sizes: S (36-37), M (38-39), L (40-41).</p>",
    tags: ["footwear", "jutti", "wedding"],
    attrs: { material: "leather", pattern: "embroidered", occasion: ["wedding", "diwali"] },
    axes: { size: ["s", "m", "l"], colour: ["gold", "red"] },
    stock: 4,
    images: 2,
    ageDays: 95,
  },
  {
    n: 32,
    title: "Kolhapuri Chappal",
    category: "footwear",
    seller: 2,
    price: 1199,
    cost: 480,
    tax: 500,
    hsn: "6403",
    weight: 450,
    short: "Vegetable-tanned leather kolhapuris from Kolhapur.",
    desc: "<p>The classic. Bag-tanned leather, braided straps, no nails - held together entirely by leather thread.</p><p>Sizes: S (38), M (40), L (42), XL (44).</p>",
    tags: ["footwear", "kolhapuri", "menswear"],
    attrs: { material: "leather", pattern: "solid", occasion: ["everyday"] },
    axes: { size: ["s", "m", "l", "xl"], colour: ["brown"] },
    stock: 7,
    images: 2,
    ageDays: 150,
  },
  {
    n: 33,
    title: "Kids' Mulmul Jhabla Set",
    category: "kids-wear",
    seller: 2,
    price: 899,
    cost: 350,
    tax: 0,
    hsn: "6209",
    weight: 150,
    short: "Soft mulmul jhabla and shorts, hand-printed polka dots.",
    desc: "<p>Two-piece set in double-layered mulmul, block printed with polka dots using azo-free dyes. Snap buttons at the shoulder.</p><p>XS 6-12 months, S 1-2 years.</p>",
    flags: { newArrival: true },
    tags: ["kids", "mulmul", "gift"],
    attrs: { fabric: "mulmul", pattern: "polka-dot", occasion: ["birthday", "everyday"] },
    axes: { size: ["xs", "s"], colour: ["yellow", "pink"] },
    stock: 6,
    images: 2,
    ageDays: 10,
  },

  // ---- Jewellery (Rangrez Jewels = 3) ---------------------------------------
  {
    n: 34,
    title: "Oxidised Silver Jhumka Earrings",
    category: "earrings",
    seller: 3,
    price: 699,
    cost: 260,
    tax: 500,
    hsn: "7117",
    weight: 24,
    short: "Classic bell jhumkas with a ghungroo drop.",
    desc: "<p>German-silver alloy, oxidised by hand for an antique finish. Push-back closure, nickel-free posts. 5 cm drop.</p>",
    flags: { bestseller: true },
    tags: ["earrings", "oxidised", "everyday"],
    attrs: { material: "metal", "metal-type": "oxidised-silver", "stone-type": "none", "closure-type": "push-back", occasion: ["everyday", "diwali"] },
    axes: { colour: ["silver"] },
    stock: 25,
    images: 2,
    ageDays: 150,
  },
  {
    n: 35,
    title: "Meenakari Chandbali Earrings",
    category: "earrings",
    seller: 3,
    price: 1299,
    sale: 999,
    cost: 480,
    tax: 500,
    hsn: "7117",
    weight: 30,
    short: "Hand-enamelled crescents with pearl drops.",
    desc: "<p>Brass base, gold-plated and hand-enamelled (meenakari) in Jaipur, finished with freshwater pearl drops. Hook closure.</p>",
    flags: { trending: true },
    tags: ["earrings", "meenakari", "wedding"],
    attrs: { material: "brass", "metal-type": "gold-plated", "stone-type": "meenakari", "closure-type": "hook", occasion: ["wedding", "diwali"] },
    axes: { colour: ["red", "green", "blue"] },
    stock: 6,
    images: 3,
    ageDays: 70,
  },
  {
    n: 36,
    title: "Terracotta Bead Necklace",
    category: "necklaces",
    seller: 3,
    price: 899,
    cost: 320,
    tax: 500,
    hsn: "7117",
    weight: 60,
    short: "Hand-rolled terracotta beads, painted and strung on cotton cord.",
    desc: "<p>Beads shaped and fired by hand, painted in earthy tones and strung with brass spacers. Adjustable cotton cord, 45 cm.</p>",
    tags: ["necklace", "terracotta", "boho"],
    attrs: { material: "terracotta", "metal-type": "alloy", "stone-type": "terracotta", length: 45, occasion: ["everyday"] },
    axes: { colour: ["orange", "multicolour"] },
    stock: 10,
    images: 2,
    ageDays: 110,
  },
  {
    n: 37,
    title: "Kundan Choker Necklace",
    category: "necklaces",
    seller: 3,
    price: 3499,
    cost: 1500,
    tax: 500,
    hsn: "7117",
    weight: 85,
    short: "Bridal-style kundan choker with pearl hangings.",
    desc: "<p>Glass kundan stones set by hand in a gold-plated brass base, backed with meenakari. Adjustable dori closure. 38 cm.</p>",
    flags: { featured: true },
    tags: ["necklace", "kundan", "wedding", "bridal"],
    attrs: { material: "brass", "metal-type": "gold-plated", "stone-type": "kundan", length: 38, occasion: ["wedding"] },
    axes: { colour: ["gold"] },
    stock: "low",
    images: 3,
    ageDays: 40,
  },
  {
    n: 38,
    title: "Thread-wrapped Bangle Set (Set of 6)",
    category: "bracelets-and-bangles",
    seller: 3,
    price: 549,
    cost: 200,
    tax: 500,
    hsn: "7117",
    weight: 90,
    short: "Silk thread over metal bases with gota trim.",
    desc: "<p>Six bangles wrapped by hand in silk thread and trimmed with gota. Sizes: Small 2.4, Medium 2.6, Large 2.8.</p>",
    tags: ["bangles", "thread", "wedding"],
    attrs: { material: "thread", "metal-type": "alloy", "stone-type": "none", occasion: ["wedding", "raksha-bandhan"] },
    axes: { colour: ["red", "pink", "blue"], size: ["small", "medium", "large"] },
    stock: 5,
    images: 2,
    ageDays: 100,
  },
  {
    n: 39,
    title: "Engraved Brass Cuff Bracelet (Personalised)",
    category: "bracelets-and-bangles",
    seller: 3,
    price: 1199,
    cost: 450,
    tax: 500,
    hsn: "7117",
    weight: 40,
    short: "Hand-hammered brass cuff engraved with your words.",
    desc: "<p>A 1.5 cm brass cuff hammered and engraved by hand with up to 20 characters. Choose a polished or antique finish. Adjustable.</p>",
    tags: ["bracelet", "personalised", "brass"],
    attrs: { material: "brass", "metal-type": "brass", "stone-type": "none", occasion: ["anniversary", "birthday"] },
    axes: { colour: ["gold"], size: ["small", "medium"] },
    stock: 8,
    images: 2,
    ageDays: 90,
    customization: [
      { type: "ENGRAVING", label: "Engraving text", placeholder: "always & forever", isRequired: true, maxLength: 20 },
      {
        type: "COLOR_SELECT",
        label: "Finish",
        isRequired: true,
        choices: [
          { value: "polished", label: "Polished" },
          { value: "antique", label: "Antique" },
        ],
      },
    ],
  },
  {
    n: 40,
    title: "Sterling Silver Lotus Ring",
    category: "rings",
    seller: 3,
    price: 1499,
    cost: 600,
    tax: 500,
    hsn: "7113",
    weight: 5,
    short: "925 silver lotus, open shank - adjustable.",
    desc: "<p>Cast and finished by hand in 925 sterling silver. Open shank fits sizes 12-18.</p>",
    tags: ["ring", "silver", "everyday"],
    attrs: { material: "metal", "metal-type": "sterling-silver", "stone-type": "none", occasion: ["everyday"] },
    axes: { colour: ["silver"] },
    stock: 12,
    images: 2,
    ageDays: 60,
  },
  {
    n: 41,
    title: "Semi-precious Stone Statement Ring",
    category: "rings",
    seller: 3,
    price: 1899,
    cost: 750,
    tax: 500,
    hsn: "7117",
    weight: 9,
    short: "Green onyx or amethyst in a silver-plated bezel.",
    desc: "<p>A bold oval cabochon in a hand-formed bezel. Choose green onyx or amethyst. Adjustable band.</p>",
    flags: { newArrival: true },
    tags: ["ring", "statement", "stone"],
    attrs: { material: "stone", "metal-type": "silver-plated", "stone-type": "semi-precious", occasion: ["everyday", "birthday"] },
    axes: { colour: ["green", "purple"] },
    stock: 4,
    images: 2,
    ageDays: 5,
  },
  {
    n: 42,
    title: "Ghungroo Anklets (Pair)",
    category: "anklets",
    seller: 3,
    price: 799,
    cost: 300,
    tax: 500,
    hsn: "7117",
    weight: 45,
    short: "Oxidised chain anklets with tiny ghungroo bells.",
    desc: "<p>German silver chain with 24 ghungroo bells per anklet. Lobster clasp with a 3 cm extender. 25 cm.</p>",
    tags: ["anklet", "oxidised", "everyday"],
    attrs: { material: "metal", "metal-type": "german-silver", "stone-type": "none", length: 25, occasion: ["everyday"] },
    axes: { colour: ["silver"] },
    stock: 18,
    images: 2,
    ageDays: 130,
  },
  {
    n: 43,
    title: "Temple Jewellery Set",
    category: "jewellery-sets",
    seller: 3,
    price: 4999,
    cost: 2200,
    tax: 500,
    hsn: "7117",
    weight: 140,
    short: "Lakshmi pendant necklace with matching jhumkas, pearl-lined.",
    desc: "<p>Antique gold-plated temple set inspired by South Indian bridal jewellery: a Lakshmi pendant necklace and matching jhumkas lined with pearls.</p>",
    flags: { featured: true },
    tags: ["jewellery-set", "temple", "bridal"],
    attrs: { material: "brass", "metal-type": "gold-plated", "stone-type": "pearl", occasion: ["wedding"] },
    axes: { colour: ["gold"] },
    stock: "low",
    images: 3,
    ageDays: 50,
  },

  // ---- Gifts (Paper & Pine = 5, platform) -----------------------------------
  {
    n: 44,
    title: "Personalised Name Mug, Hand-lettered",
    category: "personalised-mugs",
    seller: 5,
    price: 449,
    cost: 160,
    tax: 1200,
    hsn: "6912",
    weight: 350,
    short: "Your name in brush lettering on a 330 ml ceramic mug.",
    desc: "<h3>Made for one person</h3><p>Hand-lettered in the studio and kiln-fired so it never fades. Dishwasher and microwave safe.</p><p>Up to 15 characters.</p>",
    flags: { bestseller: true },
    tags: ["mug", "personalised", "gift", "birthday"],
    attrs: { occasion: ["birthday", "anniversary"], material: "ceramic", capacity: 330, shape: "round", theme: ["quotes"] },
    axes: { colour: ["white", "black"] },
    stock: 40,
    images: 2,
    ageDays: 160,
    customization: [
      { type: "NAME", label: "Name on the mug", placeholder: "Aarav", isRequired: true, minLength: 1, maxLength: 15 },
      {
        type: "COLOR_SELECT",
        label: "Lettering colour",
        isRequired: true,
        choices: [
          { value: "gold", label: "Gold" },
          { value: "black", label: "Black" },
          { value: "teal", label: "Teal" },
        ],
      },
      { type: "MESSAGE", label: "Short message inside the rim", maxLength: 60 },
    ],
  },
  {
    n: 45,
    title: "Photo Mug with Custom Message",
    category: "personalised-mugs",
    seller: 5,
    price: 599,
    cost: 220,
    tax: 1200,
    hsn: "6912",
    weight: 360,
    short: "Wrap-around photo print with your message, 350 ml.",
    desc: "<p>Upload one photo and a message - we print it edge to edge on a white 350 ml mug using sublimation ink. Dishwasher safe.</p>",
    flags: { trending: true },
    tags: ["mug", "personalised", "photo", "gift"],
    attrs: { occasion: ["birthday", "valentines-day"], material: "ceramic", capacity: 350, shape: "round", theme: ["quotes"] },
    axes: { colour: ["white"] },
    stock: 35,
    images: 2,
    ageDays: 120,
    customization: [
      { type: "PHOTO", label: "Photo", helpText: "JPEG or PNG, at least 1500 px wide.", isRequired: true, maxFiles: 1, allowedMimeTypes: IMAGE_MIMES },
      { type: "MESSAGE", label: "Message", placeholder: "Happy birthday, Maa!", isRequired: true, maxLength: 80 },
      { type: "INSTRUCTIONS", label: "Anything else?", maxLength: 200 },
    ],
  },
  {
    n: 46,
    title: "Couple Mug Set with Names",
    category: "personalised-mugs",
    seller: 5,
    price: 899,
    cost: 320,
    tax: 1200,
    hsn: "6912",
    weight: 700,
    short: "Two mugs, two names, one design that joins when placed together.",
    desc: "<p>A pair of 330 ml mugs printed with your names and a linking design. Boxed together, ready to gift.</p>",
    tags: ["mug", "personalised", "anniversary", "couple"],
    attrs: { occasion: ["anniversary", "valentines-day", "wedding"], material: "ceramic", capacity: 330, shape: "round", theme: ["quotes"] },
    axes: { colour: ["white", "pink"] },
    stock: 20,
    images: 2,
    ageDays: 100,
    customization: [
      { type: "NAME", label: "First name", isRequired: true, maxLength: 15 },
      { type: "NAME", label: "Second name", isRequired: true, maxLength: 15 },
      {
        type: "DESIGN_SELECT",
        label: "Design",
        isRequired: true,
        choices: [
          { value: "heart", label: "Half hearts" },
          { value: "infinity", label: "Infinity loop", priceDeltaPaise: 5000 },
          { value: "initials", label: "Monogram initials" },
        ],
      },
    ],
  },
  {
    n: 47,
    title: "Engraved Wooden Photo Frame (Personalised)",
    category: "photo-frames",
    seller: 5,
    price: 999,
    cost: 380,
    tax: 1200,
    hsn: "4414",
    weight: 600,
    short: "Solid pine frame laser-engraved with your message.",
    desc: "<p>Solid pine, hand-sanded and engraved with up to 40 characters along the bottom rail. Glass front, easel back and wall hook.</p><p>Optionally upload a photo and we print and insert it for you.</p>",
    flags: { featured: true },
    tags: ["frame", "personalised", "anniversary", "housewarming"],
    attrs: { occasion: ["anniversary", "housewarming", "birthday"], material: "wood", "frame-type": "wooden-frame", theme: ["quotes"] },
    axes: { size: ["8x10", "12x16"], colour: ["brown", "white"] },
    variantPrices: { "12x16": 300 },
    stock: 10,
    images: 2,
    ageDays: 140,
    customization: [
      { type: "ENGRAVING", label: "Engraving", placeholder: "Our first home · 2026", isRequired: true, maxLength: 40 },
      { type: "PHOTO", label: "Photo to print and insert", helpText: "Optional. We print on matte photo paper.", maxFiles: 1, allowedMimeTypes: IMAGE_MIMES, priceDeltaPaise: 15000 },
    ],
  },
  {
    n: 48,
    title: "Collage Photo Frame (6 Photos)",
    category: "photo-frames",
    seller: 5,
    price: 1499,
    cost: 560,
    tax: 1200,
    hsn: "4414",
    weight: 1400,
    short: "Six 4×6 openings in a black wooden frame, photos printed for you.",
    desc: "<p>Upload six photos; we print them on archival paper and mount them behind glass in a black wooden frame. Add a short caption for the centre plaque.</p>",
    tags: ["frame", "personalised", "photo", "birthday"],
    attrs: { occasion: ["birthday", "anniversary"], material: "wood", "frame-type": "wooden-frame", theme: ["quotes"] },
    axes: { size: ["12x16", "18x24"], colour: ["black"] },
    variantPrices: { "18x24": 500 },
    stock: 6,
    images: 2,
    ageDays: 80,
    customization: [
      { type: "PHOTO", label: "Six photos", isRequired: true, maxFiles: 6, allowedMimeTypes: IMAGE_MIMES },
      { type: "MESSAGE", label: "Centre caption", maxLength: 40 },
    ],
  },
  {
    n: 49,
    title: "Diwali Gift Hamper – Sweets & Diyas",
    category: "gift-hampers",
    seller: null,
    brand: "DIY Baazar Originals",
    price: 1999,
    sale: 1799,
    saleWindow: "future",
    cost: 900,
    tax: 500,
    hsn: "1704",
    weight: 1800,
    short: "Handmade diyas, dry-fruit laddoos and a soy tealight set in a cane basket.",
    desc: "<p>Curated from three of our sellers: four hand-painted terracotta diyas, a box of dry-fruit laddoos, a soy tealight set and a hand-written card, packed in a cane basket.</p>",
    flags: { featured: true },
    tags: ["hamper", "diwali", "festive", "gift"],
    attrs: { occasion: ["diwali", "housewarming"], material: "cane", theme: ["festive"] },
    stock: 50,
    images: 2,
    ageDays: 20,
  },
  {
    n: 50,
    title: "Self-care Hamper with Soy Candle & Journal",
    category: "gift-hampers",
    seller: 5,
    price: 2499,
    cost: 1100,
    tax: 500,
    hsn: "4820",
    weight: 1200,
    short: "A candle, a handmade journal, a pen and a ceramic mug in a kraft box.",
    desc: "<p>Everything for a slow Sunday: a lavender soy candle, a handmade-paper journal, a wooden pen and a stoneware mug, boxed with a hand-written note.</p>",
    flags: { newArrival: true },
    tags: ["hamper", "self-care", "gift", "birthday"],
    attrs: { occasion: ["birthday", "anniversary"], material: "paper", theme: ["nature"] },
    stock: 12,
    images: 2,
    ageDays: 14,
  },
  {
    n: 51,
    title: "Corporate Desk Gift Set (Engraved)",
    category: "corporate-gifts",
    seller: null,
    brand: "DIY Baazar Originals",
    price: 1799,
    cost: 800,
    tax: 1200,
    hsn: "4420",
    weight: 900,
    short: "Wooden pen, card holder and coaster set engraved with your logo text.",
    desc: "<p>A sheesham pen, a business-card holder and two coasters, each engraved with your company name. Bulk pricing on request above 50 sets.</p>",
    tags: ["corporate", "engraved", "gift"],
    attrs: { occasion: ["corporate"], material: "wood", theme: ["quotes"] },
    axes: { colour: ["brown", "black"] },
    stock: 120,
    images: 2,
    ageDays: 200,
    maxOrderQty: 500,
    customization: [
      { type: "ENGRAVING", label: "Company name / tagline", isRequired: true, maxLength: 30 },
      {
        type: "DESIGN_SELECT",
        label: "Packaging",
        isRequired: true,
        choices: [
          { value: "kraft", label: "Kraft box" },
          { value: "premium", label: "Premium rigid box", priceDeltaPaise: 25000 },
        ],
      },
      { type: "INSTRUCTIONS", label: "Logo file or notes", helpText: "Share a vector logo link if you have one.", maxLength: 300 },
    ],
  },
  {
    n: 52,
    title: "Personalised Leather Keychain",
    category: "keychains",
    seller: 5,
    price: 299,
    cost: 90,
    tax: 1200,
    hsn: "4205",
    weight: 25,
    short: "Full-grain leather tag stamped with your initials.",
    desc: "<p>Hand-cut leather tag with brass hardware, hot-stamped with up to four initials. Choose the stitching colour.</p>",
    flags: { bestseller: true },
    tags: ["keychain", "personalised", "leather", "gift"],
    attrs: { occasion: ["birthday", "everyday"], material: "leather", theme: ["quotes"] },
    axes: { colour: ["brown", "black", "red"] },
    stock: 60,
    images: 2,
    ageDays: 170,
    customization: [
      { type: "ENGRAVING", label: "Initials", placeholder: "A.K.", isRequired: true, maxLength: 4 },
      {
        type: "COLOR_SELECT",
        label: "Stitching colour",
        choices: [
          { value: "natural", label: "Natural" },
          { value: "red", label: "Red" },
          { value: "navy", label: "Navy" },
        ],
      },
    ],
  },
  {
    n: 53,
    title: "Resin Pressed-flower Keychain",
    category: "keychains",
    seller: 5,
    price: 249,
    cost: 70,
    tax: 1200,
    hsn: "3926",
    weight: 20,
    short: "Real dried flowers set in clear resin.",
    desc: "<p>Garden flowers pressed and preserved in crystal-clear resin, with a gold-tone clasp. No two are alike.</p>",
    tags: ["keychain", "resin", "floral", "gift"],
    attrs: { occasion: ["everyday", "birthday"], material: "resin", theme: ["floral"] },
    axes: { colour: ["pink", "purple", "blue"] },
    stock: 30,
    images: 2,
    ageDays: 45,
  },
  {
    n: 54,
    title: "Personalised Wooden Music Box",
    category: "personalised-gifts",
    seller: 5,
    price: 1899,
    cost: 780,
    tax: 1200,
    hsn: "9208",
    weight: 500,
    short: "Hand-crank music box engraved with your message.",
    desc: "<p>A walnut-stained wooden music box with a hand-crank movement. Engrave up to 40 characters on the lid and pick a tune.</p>",
    flags: { trending: true },
    tags: ["personalised", "anniversary", "gift", "music"],
    attrs: { occasion: ["anniversary", "valentines-day", "birthday"], material: "wood", theme: ["quotes"] },
    axes: { colour: ["brown"] },
    stock: 8,
    images: 2,
    ageDays: 70,
    customization: [
      { type: "ENGRAVING", label: "Lid engraving", isRequired: true, maxLength: 40 },
      {
        type: "DESIGN_SELECT",
        label: "Tune",
        isRequired: true,
        choices: [
          { value: "tum-hi-ho", label: "Tum Hi Ho" },
          { value: "kal-ho-naa-ho", label: "Kal Ho Naa Ho" },
          { value: "custom", label: "Custom tune (we source it)", priceDeltaPaise: 30000 },
        ],
      },
      { type: "INSTRUCTIONS", label: "Notes for the maker", maxLength: 200 },
    ],
  },
  {
    n: 55,
    title: "Custom Star Map Print",
    category: "personalised-gifts",
    seller: null,
    brand: "DIY Baazar Originals",
    price: 1299,
    cost: 350,
    tax: 1200,
    hsn: "4911",
    weight: 200,
    short: "The night sky over a place and date that matters, printed on cotton paper.",
    desc: "<p>Tell us the date and place; we plot the exact night sky and print it on 300 gsm cotton rag paper with your title line. Unframed.</p>",
    tags: ["personalised", "print", "anniversary", "gift"],
    attrs: { occasion: ["anniversary", "birthday", "valentines-day"], material: "paper", theme: ["quotes"] },
    axes: { colour: ["black", "indigo"] },
    stock: 25,
    images: 2,
    ageDays: 95,
    customization: [
      { type: "MESSAGE", label: "Date and place", placeholder: "14 Feb 2020, Jaipur", isRequired: true, maxLength: 80 },
      { type: "NAME", label: "Title line", placeholder: "The night we met", maxLength: 40 },
      {
        type: "DESIGN_SELECT",
        label: "Print size",
        isRequired: true,
        choices: [
          { value: "a4", label: "A4" },
          { value: "a3", label: "A3", priceDeltaPaise: 40000 },
        ],
      },
    ],
  },

  // ---- Stationery (Paper & Pine = 5, Kalakriti = 1) --------------------------
  {
    n: 56,
    title: "Handmade Paper Journal, Leather Bound",
    category: "notebooks-and-journals",
    seller: 5,
    price: 899,
    cost: 340,
    tax: 1200,
    hsn: "4820",
    weight: 420,
    short: "200 deckle-edged pages of cotton rag paper in a soft leather cover.",
    desc: "<p>Cotton rag paper made in Sanganer, bound by hand into a soft leather wrap with a tie closure. Takes fountain-pen ink without feathering.</p>",
    flags: { bestseller: true },
    tags: ["journal", "stationery", "leather"],
    attrs: { theme: ["nature"], pattern: "solid", size: "medium" },
    axes: { colour: ["brown", "teal"] },
    stock: 20,
    images: 2,
    ageDays: 150,
  },
  {
    n: 57,
    title: "Recycled Cotton Rag Notebooks (Set of 3)",
    category: "notebooks-and-journals",
    seller: 5,
    price: 499,
    cost: 170,
    tax: 1200,
    hsn: "4820",
    weight: 300,
    short: "A5 notebooks with screen-printed covers, 64 pages each.",
    desc: "<p>Three A5 notebooks made from recycled cotton rag, thread-bound with screen-printed geometric covers.</p>",
    flags: { newArrival: true },
    tags: ["notebook", "stationery", "recycled"],
    attrs: { theme: ["abstract"], pattern: "geometric", size: "small" },
    axes: { colour: ["multicolour"] },
    stock: 40,
    images: 1,
    ageDays: 9,
  },
  {
    n: 58,
    title: "Undated Weekly Planner",
    category: "planners",
    seller: 5,
    price: 1199,
    sale: 999,
    cost: 420,
    tax: 1200,
    hsn: "4820",
    weight: 520,
    short: "52 undated weeks, habit trackers and a linen hardcover.",
    desc: "<p>Start any week of the year. 52 weekly spreads with habit trackers, monthly reviews and a pocket at the back. Linen-wrapped hardcover, lay-flat binding.</p>",
    tags: ["planner", "stationery", "productivity"],
    attrs: { theme: ["quotes"], size: "large" },
    axes: { colour: ["beige", "green"] },
    stock: 15,
    images: 2,
    ageDays: 60,
  },
  {
    n: 59,
    title: "Engraved Wooden Pen with Box (Personalised)",
    category: "pens-and-pencils",
    seller: 5,
    price: 649,
    cost: 220,
    tax: 1200,
    hsn: "9608",
    weight: 80,
    short: "Rosewood ballpoint engraved with a name, in a matching box.",
    desc: "<p>Rosewood barrel with brass fittings, engraved with up to 20 characters, in a wooden gift box. Refills are standard Parker-style.</p>",
    tags: ["pen", "personalised", "corporate", "gift"],
    attrs: { theme: ["quotes"], pattern: "solid" },
    axes: { colour: ["brown", "black"] },
    stock: 30,
    images: 2,
    ageDays: 110,
    customization: [
      { type: "ENGRAVING", label: "Name to engrave", isRequired: true, maxLength: 20 },
      {
        type: "DESIGN_SELECT",
        label: "Ink",
        isRequired: true,
        choices: [
          { value: "blue", label: "Blue ink" },
          { value: "black", label: "Black ink" },
        ],
      },
    ],
  },
  {
    n: 60,
    title: "Handmade Greeting Cards (Set of 5)",
    category: "greeting-cards",
    seller: 5,
    price: 399,
    cost: 130,
    tax: 1200,
    hsn: "4909",
    weight: 120,
    short: "Block-printed cards with envelopes, blank inside.",
    desc: "<p>Five A6 cards on handmade paper, block printed with festive motifs, each with a matching envelope. Blank inside.</p>",
    tags: ["cards", "stationery", "festive"],
    attrs: { theme: ["festive", "floral"], pattern: "floral", size: "small" },
    axes: { colour: ["multicolour"] },
    stock: 45,
    images: 1,
    ageDays: 75,
  },
  {
    n: 61,
    title: "Custom Calligraphy Greeting Card",
    category: "greeting-cards",
    seller: 5,
    price: 249,
    cost: 60,
    tax: 1200,
    hsn: "4909",
    weight: 40,
    short: "Your message hand-lettered in brush calligraphy.",
    desc: "<p>One A5 card on cotton paper with your message written by hand in brush calligraphy. Tell us the recipient's name and what you want to say.</p>",
    tags: ["cards", "personalised", "calligraphy"],
    attrs: { theme: ["quotes"], pattern: "solid", size: "small" },
    axes: { colour: ["white", "beige"] },
    stock: 80,
    images: 1,
    ageDays: 50,
    customization: [
      { type: "NAME", label: "Recipient's name", isRequired: true, maxLength: 30 },
      { type: "MESSAGE", label: "Message", isRequired: true, maxLength: 120 },
    ],
  },
  {
    n: 62,
    title: "Wooden Desk Organiser",
    category: "desk-accessories",
    seller: 1,
    price: 1299,
    cost: 500,
    tax: 1200,
    hsn: "4420",
    weight: 800,
    dims: [28, 12, 10],
    short: "Sheesham organiser with a phone slot and pen wells.",
    desc: "<p>Solid sheesham with two pen wells, a phone slot and a shallow tray for clips. Natural oil finish.</p>",
    tags: ["desk", "wood", "office"],
    attrs: { theme: ["nature"], pattern: "solid", size: "medium" },
    axes: { colour: ["brown"] },
    stock: 9,
    images: 2,
    ageDays: 130,
  },
  {
    n: 63,
    title: "Hand-drawn Sticker Sheets (Pack of 4)",
    category: "stickers-and-washi-tape",
    seller: 5,
    price: 199,
    cost: 50,
    tax: 1200,
    hsn: "4911",
    weight: 30,
    short: "Kiss-cut vinyl stickers of Indian animals and street food.",
    desc: "<p>Four A5 sheets of waterproof vinyl stickers drawn by our in-house illustrator: Indian birds, street food, monsoon and festivals.</p>",
    flags: { trending: true },
    tags: ["stickers", "stationery", "kids"],
    attrs: { theme: ["kids", "animals"], pattern: "abstract", size: "small" },
    axes: { colour: ["multicolour"] },
    stock: 100,
    images: 1,
    ageDays: 35,
  },
  {
    n: 64,
    title: "Floral Washi Tape Set",
    category: "stickers-and-washi-tape",
    seller: 5,
    price: 349,
    cost: 110,
    tax: 1200,
    hsn: "4811",
    weight: 60,
    short: "Six rolls of rice-paper washi tape in botanical prints.",
    desc: "<p>Six 15 mm rolls, 5 m each, printed with pressed-flower and leaf patterns. Repositionable and tearable by hand.</p>",
    tags: ["washi", "stationery", "floral"],
    attrs: { theme: ["floral"], pattern: "floral", size: "small" },
    axes: { colour: ["pink", "green"] },
    stock: "out",
    images: 1,
    ageDays: 120,
  },

  // ---- Paintings (Mithila Art House = 4) -------------------------------------
  {
    n: 65,
    title: "Madhubani Fish Motif Painting",
    category: "madhubani",
    seller: 4,
    price: 3499,
    cost: 1400,
    tax: 1200,
    hsn: "9701",
    weight: 400,
    short: "Twin fish - a symbol of prosperity - in natural pigments on handmade paper.",
    desc: "<p>Painted with bamboo nib and natural pigments (turmeric, indigo, lampblack) on acid-free handmade paper. The double-fish motif is a traditional wish for prosperity.</p><p>Available unframed or in a hand-finished wooden frame.</p>",
    flags: { featured: true },
    tags: ["madhubani", "folk-art", "painting"],
    attrs: { "painting-medium": "natural-pigments", theme: ["nature", "animals"], style: "folk", dimensions: "12 × 16 in (unframed)" },
    axes: { size: ["12x16", "18x24"], "frame-type": ["unframed", "wooden-frame"] },
    variantPrices: { "18x24": 1500, "wooden-frame": 800 },
    stock: [2, 1, 2, 1],
    images: 2,
    ageDays: 90,
  },
  {
    n: 66,
    title: "Madhubani Tree of Life",
    category: "madhubani",
    seller: 4,
    price: 5999,
    cost: 2600,
    tax: 1200,
    hsn: "9701",
    weight: 700,
    short: "A densely detailed Tree of Life with birds and peacocks.",
    desc: "<p>A signature Mithila composition: the Tree of Life crowded with birds, peacocks and fish, drawn in fine line work and filled with natural colour. About sixty hours of work.</p>",
    flags: { trending: true },
    tags: ["madhubani", "folk-art", "painting", "statement"],
    attrs: { "painting-medium": "natural-pigments", theme: ["nature", "spiritual"], style: "folk", dimensions: "18 × 24 in (unframed)" },
    axes: { size: ["18x24", "24x36"], "frame-type": ["unframed", "floating-frame"] },
    variantPrices: { "24x36": 3000, "floating-frame": 1500 },
    stock: "low",
    images: 3,
    ageDays: 40,
  },
  {
    n: 67,
    title: "Warli Village Life Canvas",
    category: "warli",
    seller: 4,
    price: 2799,
    cost: 1100,
    tax: 1200,
    hsn: "9701",
    weight: 600,
    short: "White Warli figures dancing, farming and celebrating on a terracotta ground.",
    desc: "<p>Traditional Warli stick figures painted in white acrylic on a hand-tinted terracotta ground, stretched on pine bars. Ready to hang.</p>",
    tags: ["warli", "tribal", "painting"],
    attrs: { "painting-medium": "acrylic", theme: ["tribal"], style: "folk" },
    axes: { size: ["12x16", "18x24"], "frame-type": ["stretched-canvas"] },
    variantPrices: { "18x24": 1200 },
    stock: 3,
    images: 2,
    ageDays: 70,
  },
  {
    n: 68,
    title: "Abstract Monsoon Canvas",
    category: "canvas-paintings",
    seller: 4,
    price: 7499,
    sale: 6499,
    cost: 3000,
    tax: 1200,
    hsn: "9701",
    weight: 1800,
    short: "Layered acrylic in indigo, slate and rain-grey on a gallery-wrapped canvas.",
    desc: "<p>An original abstract in heavy-body acrylic with palette-knife texture, gallery-wrapped over 1.5 in bars so no frame is needed. Signed on the reverse.</p>",
    flags: { featured: true },
    tags: ["abstract", "canvas", "painting", "original"],
    attrs: { "painting-medium": "acrylic", theme: ["abstract"], style: "contemporary", dimensions: "24 × 36 × 1.5 in" },
    axes: { size: ["24x36"], "frame-type": ["gallery-wrap"] },
    stock: "low",
    images: 2,
    ageDays: 25,
  },
  {
    n: 69,
    title: "Watercolour – Ghats of Varanasi",
    category: "watercolour",
    seller: 4,
    price: 2199,
    cost: 850,
    tax: 1200,
    hsn: "9701",
    weight: 300,
    short: "Dawn on the ghats in loose, luminous watercolour.",
    desc: "<p>Painted on 300 gsm cold-pressed paper from sketches made on the ghats at dawn. Limited to one original per size.</p>",
    tags: ["watercolour", "cityscape", "painting"],
    attrs: { "painting-medium": "watercolour", theme: ["cityscape", "spiritual"], style: "contemporary" },
    axes: { size: ["8x10", "12x16"], "frame-type": ["unframed", "wooden-frame"] },
    variantPrices: { "12x16": 900, "wooden-frame": 700 },
    stock: 4,
    images: 2,
    ageDays: 55,
  },
  {
    n: 70,
    title: "Mandala Dot Art on Canvas",
    category: "mandala-art",
    seller: 4,
    price: 1899,
    cost: 700,
    tax: 1200,
    hsn: "9701",
    weight: 500,
    short: "Meditative dot-work mandala in jewel tones on black canvas.",
    desc: "<p>Thousands of acrylic dots placed by hand in concentric rings on a black canvas. Available stretched or in a slim wooden frame.</p>",
    flags: { bestseller: true },
    tags: ["mandala", "painting", "spiritual"],
    attrs: { "painting-medium": "acrylic", theme: ["spiritual", "abstract"], style: "modern" },
    axes: { size: ["12x16"], "frame-type": ["stretched-canvas", "wooden-frame"] },
    variantPrices: { "wooden-frame": 600 },
    stock: 5,
    images: 2,
    ageDays: 100,
  },
  {
    n: 71,
    title: "Custom Portrait from Photo (Commission)",
    category: "portraits-and-custom-paintings",
    seller: 4,
    price: 4999,
    cost: 1800,
    tax: 1200,
    hsn: "9701",
    weight: 800,
    short: "A hand-painted acrylic portrait from your photograph, in 10-14 days.",
    desc: "<h3>How it works</h3><ol><li>Upload one to three clear photos.</li><li>Tell us how many people and any background wishes.</li><li>We share a progress photo before the final coat.</li></ol><p>Painted in acrylic on canvas board; framing optional.</p>",
    flags: { featured: true },
    tags: ["portrait", "commission", "personalised", "painting"],
    attrs: { "painting-medium": "acrylic", style: "contemporary" },
    axes: { size: ["12x16", "18x24", "24x36"], "frame-type": ["unframed", "wooden-frame"] },
    variantPrices: { "18x24": 2000, "24x36": 5000, "wooden-frame": 1200 },
    stock: 5,
    images: 2,
    ageDays: 150,
    shippingNote: "Commissioned work - allow 10-14 days before dispatch.",
    customization: [
      { type: "PHOTO", label: "Reference photos", helpText: "Up to three; good light, faces in focus.", isRequired: true, maxFiles: 3, allowedMimeTypes: IMAGE_MIMES },
      {
        type: "DESIGN_SELECT",
        label: "People in the portrait",
        isRequired: true,
        choices: [
          { value: "one", label: "One person" },
          { value: "two", label: "Two people", priceDeltaPaise: 150000 },
          { value: "three-plus", label: "Three or more", priceDeltaPaise: 300000 },
        ],
      },
      { type: "INSTRUCTIONS", label: "Background, mood, anything to include", maxLength: 400 },
    ],
  },
  {
    n: 72,
    title: "Pet Portrait in Watercolour (Commission)",
    category: "portraits-and-custom-paintings",
    seller: 4,
    price: 2999,
    cost: 1000,
    tax: 1200,
    hsn: "9701",
    weight: 250,
    short: "Your pet, painted loosely in watercolour with their name lettered below.",
    desc: "<p>Send a photo of your pet and we paint a loose watercolour portrait on cotton paper, with the name hand-lettered underneath. Unframed.</p>",
    flags: { newArrival: true },
    tags: ["portrait", "pet", "commission", "watercolour"],
    attrs: { "painting-medium": "watercolour", style: "contemporary" },
    axes: { size: ["8x10", "12x16"], "frame-type": ["unframed"] },
    variantPrices: { "12x16": 800 },
    stock: 10,
    images: 2,
    ageDays: 7,
    customization: [
      { type: "PHOTO", label: "Photo of your pet", isRequired: true, maxFiles: 2, allowedMimeTypes: IMAGE_MIMES },
      { type: "NAME", label: "Pet's name", isRequired: true, maxLength: 20 },
      { type: "INSTRUCTIONS", label: "Notes", maxLength: 200 },
    ],
  },

  // ---- Non-live listings for status variety -----------------------------------
  {
    n: 73,
    title: "Terracotta Wind Chime",
    category: "wall-decor",
    seller: 7,
    price: 899,
    cost: 320,
    tax: 500,
    hsn: "6913",
    weight: 600,
    short: "Hand-shaped terracotta bells on a jute cord.",
    desc: "<p>Seven terracotta bells with wooden clappers, strung on jute. Draft listing awaiting seller approval.</p>",
    tags: ["wind-chime", "terracotta"],
    attrs: { material: "terracotta", finish: "natural", style: "rustic", weight: 600 },
    axes: { colour: ["brown"] },
    stock: "out",
    status: "DRAFT",
    images: 1,
    ageDays: 4,
  },
  {
    n: 74,
    title: "Diwali 2025 Gift Box",
    category: "gift-hampers",
    seller: null,
    brand: "DIY Baazar Originals",
    price: 1499,
    cost: 700,
    tax: 500,
    hsn: "1704",
    weight: 1200,
    short: "Last season's festive box - retired.",
    desc: "<p>Archived listing kept for order history.</p>",
    tags: ["hamper", "diwali"],
    attrs: { occasion: ["diwali"], material: "paper", theme: ["festive"] },
    stock: "out",
    status: "ARCHIVED",
    images: 1,
    ageDays: 330,
  },
];
