/** Emits a JSON map of real ids/slugs for filling dynamic route segments. */
import { db } from "@/lib/db";

async function main() {
  const [
    product,
    order,
    customer,
    seller,
    category,
    attribute,
    coupon,
    promotion,
    banner,
    page,
    post,
    blogCategory,
    ret,
    refund,
    payment,
    payout,
    user,
    role,
    review,
    inquiry,
    media,
    variant,
    template,
    job,
    subscriber,
    section,
  ] = await Promise.all([
    db.product.findFirst({ where: { status: "PUBLISHED" }, select: { id: true, slug: true } }),
    db.order.findFirst({ orderBy: { placedAt: "desc" }, select: { id: true, orderNumber: true } }),
    db.customer.findFirst({ select: { id: true, email: true } }),
    db.seller.findFirst({ where: { status: "ACTIVE" }, select: { id: true, slug: true } }),
    db.category.findFirst({ where: { parentId: null }, select: { id: true, slug: true } }),
    db.attribute.findFirst({ select: { id: true } }),
    db.coupon.findFirst({ select: { id: true } }),
    db.promotion.findFirst({ select: { id: true } }),
    db.banner.findFirst({ select: { id: true } }),
    db.cmsPage.findFirst({ where: { status: "PUBLISHED" }, select: { id: true, slug: true } }),
    db.blogPost.findFirst({ where: { status: "PUBLISHED" }, select: { id: true, slug: true } }),
    db.blogCategory.findFirst({ select: { id: true } }),
    db.returnRequest.findFirst({ select: { id: true, rmaNumber: true } }),
    db.refund.findFirst({ select: { id: true } }),
    db.orderPayment.findFirst({ select: { id: true } }),
    db.sellerPayout.findFirst({ select: { id: true } }),
    db.user.findFirst({ where: { isActive: true }, select: { id: true } }),
    db.role.findFirst({ select: { id: true } }),
    db.review.findFirst({ select: { id: true } }),
    db.contactInquiry.findFirst({ select: { id: true } }),
    db.mediaAsset.findFirst({ where: { visibility: "PUBLIC" }, select: { id: true } }),
    db.productVariant.findFirst({ select: { id: true } }),
    db.emailTemplate.findFirst({ select: { id: true, key: true } }),
    db.job.findFirst({ select: { id: true } }),
    db.newsletterSubscriber.findFirst({ select: { id: true } }),
    db.contentSection.findFirst({ select: { id: true } }),
  ]);

  const samples: Record<string, string> = {
    // by param name (global fallback)
    slug: product?.slug ?? "",
    report: "sales",
    provider: "mock",
    number: order?.orderNumber ?? "",
    rma: ret?.rmaNumber ?? "",
    pin: "110001",
    menu: "main",
    email: customer?.email ?? "",
    variantId: variant?.id ?? "",
    key: template?.key ?? "welcome",
    docId: "none",
    token: "invalid-token-probe",
    sessionToken: "probe-session",
    // route-specific: "<route>:<param>"
    "/admin/products/[id]:id": product?.id ?? "",
    "/admin/orders/[id]:id": order?.id ?? "",
    "/admin/orders/[id]/invoice:id": order?.id ?? "",
    "/admin/customers/[id]:id": customer?.id ?? "",
    "/admin/sellers/[id]:id": seller?.id ?? "",
    "/admin/categories/[id]:id": category?.id ?? "",
    "/admin/attributes/[id]:id": attribute?.id ?? "",
    "/admin/coupons/[id]:id": coupon?.id ?? "",
    "/admin/promotions/[id]:id": promotion?.id ?? "",
    "/admin/banners/[id]:id": banner?.id ?? "",
    "/admin/pages/[id]:id": page?.id ?? "",
    "/admin/blog/[id]:id": post?.id ?? "",
    "/admin/returns/[id]:id": ret?.id ?? "",
    "/admin/refunds/[id]:id": refund?.id ?? "",
    "/admin/payments/[id]:id": payment?.id ?? "",
    "/admin/payouts/[id]:id": payout?.id ?? "",
    "/admin/payouts/[id]/print:id": payout?.id ?? "",
    "/admin/users/[id]:id": user?.id ?? "",
    "/admin/roles/[id]:id": role?.id ?? "",
    "/admin/inquiries/[id]:id": inquiry?.id ?? "",
    "/admin/email-templates/[id]:id": template?.id ?? "",
    "/admin/reports/[report]:report": "sales",
    // api samples
    "/api/admin/products/[id]:id": product?.id ?? "",
    "/api/admin/orders/[id]:id": order?.id ?? "",
    "/api/admin/customers/[id]:id": customer?.id ?? "",
    "/api/admin/sellers/[id]:id": seller?.id ?? "",
    "/api/admin/categories/[id]:id": category?.id ?? "",
    "/api/admin/attributes/[id]:id": attribute?.id ?? "",
    "/api/admin/coupons/[id]:id": coupon?.id ?? "",
    "/api/admin/media/[id]:id": media?.id ?? "",
    "/api/admin/reviews/[id]:id": review?.id ?? "",
    "/api/admin/jobs/[id]:id": job?.id ?? "",
    "/api/admin/newsletter/[id]:id": subscriber?.id ?? "",
    "/api/admin/blog/categories/[id]:id": blogCategory?.id ?? "",
    "/api/admin/homepage/sections/[id]:id": section?.id ?? "",
    id: product?.id ?? "",
  };

  console.log(JSON.stringify(samples));
  await db.$disconnect();
}

void main();
